### PR TITLE
Mumble melody study page - Update device info

### PR DESCRIPTION
**Pull request by alishakodibagkar**
docs/images/Mumble_Melody_flyer.jpg: Removed old flyer, and added new one 
docs/_pages/mumble_melody_study.md: Added device information

### CODE REVIEW

**Comment by satra** [comment]
@alishakodibagkar - can you rebase your local repo on top of the master repo here?

**Comment by alishakodibagkar** [comment]
> @alishakodibagkar - can you rebase your local repo on top of the master repo here?

Done

**Comment by satra** [comment]
@alishakodibagkar - i think having two QR codes can be confusing to people. for recruitment purposes i would suggest having just one.

**Comment by alishakodibagkar** [comment]
Added flyer with 1 QR code

**Pull request merged**
