### PR TITLE
Update team_members.yml

### PR DESCRIPTION
**Pull request by jhlee-ku**
Jong-Hwan Lee added his information.

### CODE REVIEW

**Comment by jhlee-ku** [comment]
Hi, I added my info to the SI group with my photo in the "images" folder. Please let me know of any problems. Thanks, Jong-Hwan Lee

**Comment by satra** [comment]
@jhlee-ku - i think this needs one more file to be added to the PR.

**Comment by jhlee-ku** [comment]
Thanks, Satra. Now, it seems done? Please let me know if anything is necessary.

**Comment by satra** [comment]
@jhlee-ku - i don't see two files in this PR. perhaps it's being added to a different branch from the one sending this PR.

**Comment by jhlee-ku** [comment]
I hope it is now done.

**Comment by satra** [comment]
@jhlee-ku - i don't think the images folder contains your image.

**Pull request merged**
